/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



/***************************************************************/
#define BASE               0x40010800
#define GPIOA_CRH         *(volatile uint32_t *)(BASE + 0x04)
#define GPIOA_ODR         *(volatile uint32_t *)(BASE + 0x0C)
#define GPIOx_CRL         *(volatile uint32_t *)(BASE + 0x0)

#define BASE_AFIO          0x40010000
#define AFIO_EXTICR1      *(volatile uint32_t *)(BASE_AFIO + 0x08)

#define BASE_EXTI          0x40010400
#define EXTI_IMR            *(volatile uint32_t *)(BASE_EXTI + 0x0)
#define EXTI_RTSR            *(volatile uint32_t *)(BASE_EXTI + 0x08)
#define EXTI_PR            *(volatile uint32_t *)(BASE_EXTI + 0x14)
#define EXTI_SWIER         *(volatile uint32_t *)(BASE_EXTI + 0x10)

#define RCC_BASE           0x40021000
#define RCC_CR             *(volatile uint32_t *)(RCC_BASE + 0x00)
#define RCC_APBENB         *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR           *(volatile uint32_t *)(RCC_BASE + 0x04)

#define NCIV_ISRG0        *(volatile uint32_t *)( 0xE000E100)
/******************************************************************/
void Init_RCC(void)
{
	//clock configuration
	RCC_CR |= 1<<0;
	// system clock HSI 00 at bits 1:0
	RCC_CFGR |= (0b00<<0);
	// set APB No pre scaler
	RCC_CFGR |= (0b0000<<4);
	// set APB1 divided by 2
	RCC_CFGR |= (0b100<<8);
	// set APB1 divided by 4
	RCC_CFGR |= (0b101<<11);

	//Enable clock for PORTA
	RCC_APBENB |= 1<<2;
	// Enable clock for Alternate function IO
	RCC_APBENB |= 1<<0;
}

void Init_GPIOA(void)
{
	// init GPIOA pin 13
	GPIOA_CRH  &= 0xff0fffff;
	GPIOA_CRH  |= 0x00200000;
	// Enable GPIOA0 input floating
	GPIOx_CRL |= (0b0100)<<0 ;
}

void Init_AFIO(void)
{

	AFIO_EXTICR1 |= (0b0000)<<0 ;


}

void Init_EXTI(void)
{
	EXTI_IMR  |= 1<<0;
	EXTI_RTSR |= 1<<0;

}

void EXTI0_IRQHandler(void){
	// change state of port a pin 0
	GPIOA_ODR ^= 1<<13 ;

	for(int i=0; i<5000; i++);

	// clear interrupt
	EXTI_PR |= 1<<0 ;
	// generate SW Interrupt
	EXTI_SWIER |= 1<<0;


}

int main(void)
{
	Init_RCC();
    Init_GPIOA();
    Init_AFIO();
    Init_EXTI();
    // Enable interrupt inside NVIC (global interrupt)
    NCIV_ISRG0 |= 1<<6;
	while(1){
	//EXTI_SWIER |= 1<<0;
	//for(int i=0; i<5000; i++);
	}
}
